### ISSUE TITLE
How to get inAppBrowser Close event after redirect another local html page..?

### ISSUE THREAD

**Issue by Kaushik0704** [nitin-kapoor/custom-inappbrowser-plugin#1]
@nitin-kapoor I'm integrating cordova inAppBrowser Plugin in my project, but I'm getting some Issue.
how to get close event on my ajax success in my 2nd html page.

Here is my 1st html page code,
```
<input type="button" id="pay" value="PAY"></input>

<script type="text/javascript">

     $( document ).ready(function() {

          $("#pay").click(function()
          {
               var ref = cordova.InAppBrowser.open("page2.html", "_blank", "location=yes");
          });

     });

<script>
```

Here is my 2nd html page code,
```
$( document ).ready(function() {

          $.ajax({
                url: url + "EmailVerified?Email=" + $("#email").val() + "&Amount=" + RechargeValue,
                type: "POST",
                dataType: 'json',
                cache: true,
                async: true,
                success: function (data)
                {
                    //Here i want to close my inAppBrowser window is it Possible..?
                }
          });    

     });
```

**Comment by nitin-kapoor** [comment]
var ref = cordova.InAppBrowser.open('http://google.com', '_blank', 'location=yes');
ref.close();

Please have a look this might help you to close the InappBrowser window. Integrate it as per your need. You can also check Readme file of this Repo.
Sorry for late response.

**Comment by nitin-kapoor** [comment]
> @nitin-kapoor I'm integrating cordova inAppBrowser Plugin in my project, but I'm getting some Issue.
> how to get close event on my ajax success in my 2nd html page.
> 
> Here is my 1st html page code,
> 
> ```
> <input type="button" id="pay" value="PAY"></input>
> 
> <script type="text/javascript">
> 
>      $( document ).ready(function() {
> 
>           $("#pay").click(function()
>           {
>                var ref = cordova.InAppBrowser.open("page2.html", "_blank", "location=yes");
>           });
> 
>      });
> 
> <script>
> ```
> Here is my 2nd html page code,
> 
> ```
> $( document ).ready(function() {
> 
>           $.ajax({
>                 url: url + "EmailVerified?Email=" + $("#email").val() + "&Amount=" + RechargeValue,
>                 type: "POST",
>                 dataType: 'json',
>                 cache: true,
>                 async: true,
>                 success: function (data)
>                 {
>                     //Here i want to close my inAppBrowser window is it Possible..?
>                 }
>           });    
> 
>      });
> ```

https://github.com/nitin-kapoor/custom-inappbrowser-plugin/issues/1#issuecomment-425690003
